"""initial schema m4 through m23

Revision ID: 0f8802656fc2
Revises: 
Create Date: 2026-08-28 04:35:05.134843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8802656fc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_briefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brief_id', sa.String(length=24), nullable=False),
    sa.Column('analyst_type', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('conclusions_json', sa.JSON(), nullable=False),
    sa.Column('claim_refs_json', sa.JSON(), nullable=False),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('missing_data_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('key_questions_json', sa.JSON(), nullable=False),
    sa.Column('risks_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyst_briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_briefs_analyst_type'), ['analyst_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_briefs_brief_id'), ['brief_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analyst_briefs_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_briefs_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index('ix_briefs_snapshot_analyst', ['snapshot_id', 'analyst_type'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=24), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('supporting_evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('opposing_evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('fact_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'statement', name='uq_claim_snapshot_statement')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_claim_id'), ['claim_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_claims_claim_type'), ['claim_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index('ix_claims_instrument_snapshot', ['instrument_id', 'snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_status'), ['status'], unique=False)

    op.create_table('corporate_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=24), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_corporate_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_events_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('debate_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debate_id', sa.String(length=24), nullable=False),
    sa.Column('thesis_id', sa.String(length=24), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('bull_claim_id', sa.String(length=24), nullable=False),
    sa.Column('bear_claim_id', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thesis_id', 'round_no', name='uq_debate_thesis_round')
    )
    with op.batch_alter_table('debate_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debate_rounds_debate_id'), ['debate_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_debate_rounds_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debate_rounds_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debate_rounds_thesis_id'), ['thesis_id'], unique=False)
        batch_op.create_index('ix_debate_thesis_snapshot', ['thesis_id', 'snapshot_id'], unique=False)

    op.create_table('evidence_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_document_id', sa.String(length=128), nullable=True),
    sa.Column('authority_level', sa.String(length=2), nullable=False),
    sa.Column('fact_status', sa.String(length=32), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('manifest_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'content_hash', name='uq_evidence_source_content')
    )
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_instrument_time', ['instrument_id', 'available_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_available_time'), ['available_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_evidence_id'), ['evidence_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_evidence_records_evidence_type'), ['evidence_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_manifest_id'), ['manifest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_source'), ['source'], unique=False)

    op.create_table('evidence_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of', name='uq_snapshot_instrument_asof')
    )
    with op.batch_alter_table('evidence_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_snapshots_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_snapshots_snapshot_id'), ['snapshot_id'], unique=True)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.String(length=24), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('research_run_id', sa.String(length=64), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('benchmark', sa.String(length=32), nullable=False),
    sa.Column('expected_direction', sa.String(length=8), nullable=False),
    sa.Column('expected_return_min', sa.Float(), nullable=False),
    sa.Column('expected_return_max', sa.Float(), nullable=False),
    sa.Column('expected_excess_min', sa.Float(), nullable=True),
    sa.Column('expected_excess_max', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_thesis_id', sa.String(length=24), nullable=True),
    sa.Column('trigger_conditions_json', sa.JSON(), nullable=False),
    sa.Column('invalidate_conditions_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_prediction_id'), ['prediction_id'], unique=True)

    op.create_table('quality_gate_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('gate', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('findings_json', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_gate_results', schema=None) as batch_op:
        batch_op.create_index('ix_gate_results_snapshot_gate', ['snapshot_id', 'gate'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_gate_results_gate'), ['gate'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_gate_results_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_gate_results_result_id'), ['result_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_quality_gate_results_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_gate_results_status'), ['status'], unique=False)

    op.create_table('regression_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=24), nullable=False),
    sa.Column('validation_id', sa.String(length=24), nullable=False),
    sa.Column('prediction_id', sa.String(length=24), nullable=False),
    sa.Column('attributions_json', sa.JSON(), nullable=False),
    sa.Column('lesson_summary', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regression_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regression_reviews_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regression_reviews_review_id'), ['review_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_regression_reviews_validation_id'), ['validation_id'], unique=False)

    op.create_table('report_asks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ask_id', sa.String(length=24), nullable=False),
    sa.Column('report_id', sa.String(length=24), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_asks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_asks_ask_id'), ['ask_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_report_asks_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_asks_report_id'), ['report_id'], unique=False)

    op.create_table('report_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.String(length=24), nullable=False),
    sa.Column('report_id', sa.String(length=24), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.String(length=24), nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('changed_sections_json', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('markdown', sa.String(), nullable=False),
    sa.Column('html', sa.String(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'version_no', name='uq_report_version_no')
    )
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_versions_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_versions_version_id'), ['version_id'], unique=True)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.String(length=24), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('gate_status', sa.String(length=16), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('markdown', sa.String(), nullable=False),
    sa.Column('html', sa.String(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_id'), ['report_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reports_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('research_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.String(length=24), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('lesson', sa.String(), nullable=False),
    sa.Column('related_research_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_validations_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_experiences_experience_id'), ['experience_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_research_experiences_related_research_type'), ['related_research_type'], unique=False)

    op.create_table('research_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=24), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_requests_capability'), ['capability'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_requests_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_requests_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_research_requests_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_requests_status'), ['status'], unique=False)

    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_runs_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_runs_run_id'), ['run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_research_runs_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_runs_status'), ['status'], unique=False)

    op.create_table('research_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=24), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('schedule', sa.String(length=64), nullable=False),
    sa.Column('research_level', sa.String(length=32), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('running_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_tasks_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_tasks_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_tasks_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_research_tasks_task_type'), ['task_type'], unique=False)

    op.create_table('revision_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.String(length=24), nullable=False),
    sa.Column('report_id', sa.String(length=24), nullable=False),
    sa.Column('base_version_id', sa.String(length=24), nullable=False),
    sa.Column('target_section', sa.String(length=64), nullable=False),
    sa.Column('target_claim_id', sa.String(length=24), nullable=True),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('proposed_text', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('added_evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('invalidated_evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('affected_claims_json', sa.JSON(), nullable=False),
    sa.Column('confidence_change', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revision_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_proposals_base_version_id'), ['base_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_proposals_proposal_id'), ['proposal_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_revision_proposals_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_proposals_status'), ['status'], unique=False)

    op.create_table('run_manifests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manifest_id', sa.String(length=24), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code_commit', sa.String(length=64), nullable=False),
    sa.Column('config_digest', sa.String(length=64), nullable=False),
    sa.Column('provider_payload_digests_json', sa.JSON(), nullable=False),
    sa.Column('model_versions_json', sa.JSON(), nullable=False),
    sa.Column('prompt_versions_json', sa.JSON(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('environment_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checkpoints_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'manifest_id', name='uq_manifest_run')
    )
    with op.batch_alter_table('run_manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_manifests_manifest_id'), ['manifest_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_run_manifests_run_id'), ['run_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(length=24), nullable=False),
    sa.Column('thesis_id', sa.String(length=24), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=False),
    sa.Column('catalysts_json', sa.JSON(), nullable=False),
    sa.Column('risks_json', sa.JSON(), nullable=False),
    sa.Column('trigger_conditions_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thesis_id', 'kind', name='uq_scenario_thesis_kind')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_scenario_id'), ['scenario_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_scenarios_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_thesis_id'), ['thesis_id'], unique=False)

    op.create_table('source_manifests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manifest_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('requested_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('providers_attempted', sa.JSON(), nullable=False),
    sa.Column('final_status', sa.String(length=32), nullable=False),
    sa.Column('final_source', sa.String(length=128), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_manifests_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_manifests_manifest_id'), ['manifest_id'], unique=True)

    op.create_table('theses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.String(length=24), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('supporting_claims_json', sa.JSON(), nullable=False),
    sa.Column('opposing_claims_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('catalysts_json', sa.JSON(), nullable=False),
    sa.Column('risks_json', sa.JSON(), nullable=False),
    sa.Column('trigger_conditions_json', sa.JSON(), nullable=False),
    sa.Column('invalidate_conditions_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'title', name='uq_thesis_snapshot_title')
    )
    with op.batch_alter_table('theses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theses_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_theses_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_theses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_theses_thesis_id'), ['thesis_id'], unique=True)

    op.create_table('validations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('validation_id', sa.String(length=24), nullable=False),
    sa.Column('prediction_id', sa.String(length=24), nullable=False),
    sa.Column('instrument_return_pct', sa.Float(), nullable=False),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=True),
    sa.Column('excess_return_pct', sa.Float(), nullable=True),
    sa.Column('direction_correct', sa.Boolean(), nullable=True),
    sa.Column('range_hit', sa.Boolean(), nullable=False),
    sa.Column('start_price', sa.Float(), nullable=False),
    sa.Column('end_price', sa.Float(), nullable=False),
    sa.Column('benchmark_start_price', sa.Float(), nullable=True),
    sa.Column('benchmark_end_price', sa.Float(), nullable=True),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    with op.batch_alter_table('validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validations_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validations_validation_id'), ['validation_id'], unique=True)

    op.create_table('valuations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valuation_id', sa.String(length=24), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('thesis_id', sa.String(length=24), nullable=True),
    sa.Column('scenario_id', sa.String(length=24), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('computable', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('inputs_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuations_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuations_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuations_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuations_thesis_id'), ['thesis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuations_valuation_id'), ['valuation_id'], unique=True)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_instrument_id'), ['instrument_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_instrument_id'))

    op.drop_table('watchlist')
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuations_valuation_id'))
        batch_op.drop_index(batch_op.f('ix_valuations_thesis_id'))
        batch_op.drop_index(batch_op.f('ix_valuations_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_valuations_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_valuations_instrument_id'))

    op.drop_table('valuations')
    with op.batch_alter_table('validations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validations_validation_id'))
        batch_op.drop_index(batch_op.f('ix_validations_prediction_id'))

    op.drop_table('validations')
    with op.batch_alter_table('theses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theses_thesis_id'))
        batch_op.drop_index(batch_op.f('ix_theses_status'))
        batch_op.drop_index(batch_op.f('ix_theses_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_theses_instrument_id'))

    op.drop_table('theses')
    with op.batch_alter_table('source_manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_manifests_manifest_id'))
        batch_op.drop_index(batch_op.f('ix_source_manifests_instrument_id'))

    op.drop_table('source_manifests')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_thesis_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_instrument_id'))

    op.drop_table('scenarios')
    with op.batch_alter_table('run_manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_manifests_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_manifests_manifest_id'))

    op.drop_table('run_manifests')
    with op.batch_alter_table('revision_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_revision_proposals_report_id'))
        batch_op.drop_index(batch_op.f('ix_revision_proposals_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_revision_proposals_base_version_id'))

    op.drop_table('revision_proposals')
    with op.batch_alter_table('research_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_research_tasks_task_id'))
        batch_op.drop_index(batch_op.f('ix_research_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_research_tasks_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_research_tasks_instrument_id'))

    op.drop_table('research_tasks')
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_runs_status'))
        batch_op.drop_index(batch_op.f('ix_research_runs_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_research_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_research_runs_instrument_id'))

    op.drop_table('research_runs')
    with op.batch_alter_table('research_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_requests_status'))
        batch_op.drop_index(batch_op.f('ix_research_requests_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_research_requests_request_id'))
        batch_op.drop_index(batch_op.f('ix_research_requests_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_research_requests_capability'))

    op.drop_table('research_requests')
    with op.batch_alter_table('research_experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_experiences_related_research_type'))
        batch_op.drop_index(batch_op.f('ix_research_experiences_experience_id'))

    op.drop_table('research_experiences')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_reports_report_id'))
        batch_op.drop_index(batch_op.f('ix_reports_language'))
        batch_op.drop_index(batch_op.f('ix_reports_instrument_id'))

    op.drop_table('reports')
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_versions_version_id'))
        batch_op.drop_index(batch_op.f('ix_report_versions_report_id'))

    op.drop_table('report_versions')
    with op.batch_alter_table('report_asks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_asks_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_asks_mode'))
        batch_op.drop_index(batch_op.f('ix_report_asks_ask_id'))

    op.drop_table('report_asks')
    with op.batch_alter_table('regression_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regression_reviews_validation_id'))
        batch_op.drop_index(batch_op.f('ix_regression_reviews_review_id'))
        batch_op.drop_index(batch_op.f('ix_regression_reviews_prediction_id'))

    op.drop_table('regression_reviews')
    with op.batch_alter_table('quality_gate_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_gate_results_status'))
        batch_op.drop_index(batch_op.f('ix_quality_gate_results_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_quality_gate_results_result_id'))
        batch_op.drop_index(batch_op.f('ix_quality_gate_results_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_quality_gate_results_gate'))
        batch_op.drop_index('ix_gate_results_snapshot_gate')

    op.drop_table('quality_gate_results')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_due_at'))

    op.drop_table('predictions')
    with op.batch_alter_table('evidence_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_snapshots_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_snapshots_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_snapshots_as_of'))

    op.drop_table('evidence_snapshots')
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_records_source'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_manifest_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_evidence_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_content_hash'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_available_time'))
        batch_op.drop_index('ix_evidence_instrument_time')

    op.drop_table('evidence_records')
    with op.batch_alter_table('debate_rounds', schema=None) as batch_op:
        batch_op.drop_index('ix_debate_thesis_snapshot')
        batch_op.drop_index(batch_op.f('ix_debate_rounds_thesis_id'))
        batch_op.drop_index(batch_op.f('ix_debate_rounds_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_debate_rounds_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_debate_rounds_debate_id'))

    op.drop_table('debate_rounds')
    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_corporate_events_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_corporate_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_corporate_events_event_id'))

    op.drop_table('corporate_events')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_status'))
        batch_op.drop_index(batch_op.f('ix_claims_snapshot_id'))
        batch_op.drop_index('ix_claims_instrument_snapshot')
        batch_op.drop_index(batch_op.f('ix_claims_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_claims_claim_type'))
        batch_op.drop_index(batch_op.f('ix_claims_claim_id'))

    op.drop_table('claims')
    with op.batch_alter_table('analyst_briefs', schema=None) as batch_op:
        batch_op.drop_index('ix_briefs_snapshot_analyst')
        batch_op.drop_index(batch_op.f('ix_analyst_briefs_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_analyst_briefs_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_analyst_briefs_brief_id'))
        batch_op.drop_index(batch_op.f('ix_analyst_briefs_analyst_type'))

    op.drop_table('analyst_briefs')
    # ### end Alembic commands ###
