"""m5 snapshots and research runs

Revision ID: 63951c2ef1c1
Revises: dae447d704ce
Create Date: 2026-08-28 02:21:07.028295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63951c2ef1c1'
down_revision: Union[str, Sequence[str], None] = 'dae447d704ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of', name='uq_snapshot_instrument_asof')
    )
    with op.batch_alter_table('evidence_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_snapshots_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_snapshots_snapshot_id'), ['snapshot_id'], unique=True)

    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_runs_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_runs_run_id'), ['run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_research_runs_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_runs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_runs_status'))
        batch_op.drop_index(batch_op.f('ix_research_runs_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_research_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_research_runs_instrument_id'))

    op.drop_table('research_runs')
    with op.batch_alter_table('evidence_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_snapshots_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_snapshots_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_snapshots_as_of'))

    op.drop_table('evidence_snapshots')
    # ### end Alembic commands ###
