"""m8 analyst briefs and research requests

Revision ID: 7ba2d8009694
Revises: 976c2b1a4cfe
Create Date: 2026-08-28 02:41:12.554459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba2d8009694'
down_revision: Union[str, Sequence[str], None] = '976c2b1a4cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
