"""m9 scenarios and debate rounds

Revision ID: 9de7f15ae001
Revises: 7ba2d8009694
Create Date: 2026-08-28 02:47:21.012295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de7f15ae001'
down_revision: Union[str, Sequence[str], None] = '7ba2d8009694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
