"""m4 evidence records and source manifests

Revision ID: dae447d704ce
Revises: 
Create Date: 2026-08-28 02:09:27.763034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae447d704ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_document_id', sa.String(length=128), nullable=True),
    sa.Column('authority_level', sa.String(length=2), nullable=False),
    sa.Column('fact_status', sa.String(length=32), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('manifest_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'content_hash', name='uq_evidence_source_content')
    )
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_instrument_time', ['instrument_id', 'available_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_available_time'), ['available_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_evidence_id'), ['evidence_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_evidence_records_evidence_type'), ['evidence_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_manifest_id'), ['manifest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_records_source'), ['source'], unique=False)

    op.create_table('source_manifests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manifest_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('requested_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('providers_attempted', sa.JSON(), nullable=False),
    sa.Column('final_status', sa.String(length=32), nullable=False),
    sa.Column('final_source', sa.String(length=128), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_manifests_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_manifests_manifest_id'), ['manifest_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_manifests_manifest_id'))
        batch_op.drop_index(batch_op.f('ix_source_manifests_instrument_id'))

    op.drop_table('source_manifests')
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_records_source'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_manifest_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_evidence_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_content_hash'))
        batch_op.drop_index(batch_op.f('ix_evidence_records_available_time'))
        batch_op.drop_index('ix_evidence_instrument_time')

    op.drop_table('evidence_records')
    # ### end Alembic commands ###
