"""Server-side message-code localization.

Backend protocols carry stable codes (``message_code`` / ``error_code``).
When the backend must generate human text (later: report sections, SSE
narration), text is resolved from a message catalog per requested language
(``zh-CN`` / ``en-US``). Evidence original text is never translated away —
this catalog is only for UI-protocol strings generated by the backend.
"""

from __future__ import annotations

SupportedLanguage = str  # "zh-CN" | "en-US"

_CATALOGS: dict[SupportedLanguage, dict[str, str]] = {
    "zh-CN": {},
    "en-US": {},
}


def normalize_language(raw: str | None) -> SupportedLanguage:
    """Map an Accept-Language style header value to a supported language.

    ``zh*`` maps to ``zh-CN``; anything else maps to ``en-US`` (任务书 §8).
    """
    if not raw:
        return "en-US"
    first = raw.split(",")[0].strip().lower()
    if first.startswith("zh"):
        return "zh-CN"
    return "en-US"


def resolve_message(message_code: str, language: SupportedLanguage) -> str | None:
    """Resolve a message code to localized text, or None if unknown code."""
    catalog = _CATALOGS.get(language) or _CATALOGS["en-US"]
    return catalog.get(message_code)
